CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  imageurl TEXT NOT NULL,
  type INTEGER NOT NULL,
  ref_id INTEGER,
  status INTEGER NOT NULL DEFAULT 1
);
